package com.retekey;

import java.util.HashMap;
import java.util.Map;

/**
 * A US physical keyboard typing each layout's language, from the Windows layout of that language
 * (kbdlayout.info's KLC files, read exactly): only the keys whose output is the language's own —
 * non-ASCII — are mapped, so digits, punctuation and plain Latin letters keep doing what the keys
 * say, and dead keys are left alone until there is a composer to serve them (RFC-0011 G2-b) — the
 * Greek tone vowels are the soft keyboard's flicks for now, since the tonos is a dead key.
 * Greek, Hebrew, Thai and Devanagari therefore remap wholesale; German adds its umlauts and ß on
 * the right-hand keys; French puts é è ç à ù where AZERTY has them (the digit row, digits on
 * Shift, as on a real AZERTY); Turkish types ı from the i key the way its own layout does.
 * Persian has a hand-written mapper of its own for the ZWNJ; Korean, Telex and romaji have theirs.
 */
final class HardwareLayoutTables {
    private static final Map<KeyboardLayoutId, Map<String, String[]>> TABLES = new HashMap<>();

    static {
        register(KeyboardLayoutId.EL_QWERTY, new String[] {  // KBDHE, by scan code = US position
            "hardware.key.a|α|Α",
            "hardware.key.b|β|Β",
            "hardware.key.c|ψ|Ψ",
            "hardware.key.d|δ|Δ",
            "hardware.key.e|ε|Ε",
            "hardware.key.f|φ|Φ",
            "hardware.key.g|γ|Γ",
            "hardware.key.h|η|Η",
            "hardware.key.i|ι|Ι",
            "hardware.key.j|ξ|Ξ",
            "hardware.key.k|κ|Κ",
            "hardware.key.l|λ|Λ",
            "hardware.key.m|μ|Μ",
            "hardware.key.n|ν|Ν",
            "hardware.key.o|ο|Ο",
            "hardware.key.p|π|Π",
            "hardware.key.r|ρ|Ρ",
            "hardware.key.s|σ|Σ",
            "hardware.key.t|τ|Τ",
            "hardware.key.u|θ|Θ",
            "hardware.key.v|ω|Ω",
            "hardware.key.w|ς|",
            "hardware.key.x|χ|Χ",
            "hardware.key.y|υ|Υ",
            "hardware.key.z|ζ|Ζ",
        });
        register(KeyboardLayoutId.HE_STANDARD, new String[] {  // KBDHEB, by scan code = US position
            "hardware.key.a|ש|",
            "hardware.key.b|נ|",
            "hardware.key.c|ב|",
            "hardware.key.d|ג|",
            "hardware.key.e|ק|",
            "hardware.key.f|כ|",
            "hardware.key.g|ע|",
            "hardware.key.h|י|",
            "hardware.key.i|ן|",
            "hardware.key.j|ח|",
            "hardware.key.k|ל|",
            "hardware.key.l|ך|",
            "hardware.key.m|צ|",
            "hardware.key.n|מ|",
            "hardware.key.o|ם|",
            "hardware.key.p|פ|",
            "hardware.key.r|ר|",
            "hardware.key.s|ד|",
            "hardware.key.t|א|",
            "hardware.key.u|ו|",
            "hardware.key.v|ה|",
            "hardware.key.x|ס|",
            "hardware.key.y|ט|",
            "hardware.key.z|ז|",
            "hardware.keycode.55|ת|",
            "hardware.keycode.56|ץ|",
            "hardware.keycode.74|ף|",
        });
        register(KeyboardLayoutId.FR_AZERTY, new String[] {  // KBDFR, by scan code = US position
            "hardware.keycode.14|è|",
            "hardware.keycode.16|ç|",
            "hardware.keycode.68|²|",
            "hardware.keycode.69||°",
            "hardware.keycode.72||£",
            "hardware.keycode.73||µ",
            "hardware.keycode.75|ù|",
            "hardware.keycode.76||§",
            "hardware.keycode.7|à|",
            "hardware.keycode.9|é|",
        });
        register(KeyboardLayoutId.DE_QWERTZ, new String[] {  // KBDGR, by scan code = US position
            "hardware.keycode.10||§",
            "hardware.keycode.68||°",
            "hardware.keycode.69|ß|",
            "hardware.keycode.71|ü|Ü",
            "hardware.keycode.74|ö|Ö",
            "hardware.keycode.75|ä|Ä",
        });
        register(KeyboardLayoutId.TR_QWERTY, new String[] {  // KBDTUQ, by scan code = US position
            "hardware.key.i|ı|",
            "hardware.keycode.55|ö|Ö",
            "hardware.keycode.56|ç|Ç",
            "hardware.keycode.68||é",
            "hardware.keycode.71|ğ|Ğ",
            "hardware.keycode.72|ü|Ü",
            "hardware.keycode.74|ş|Ş",
            "hardware.keycode.75||İ",
        });
        register(KeyboardLayoutId.ES_QWERTY, new String[] {  // KBDSP, by scan code = US position
            "hardware.keycode.10||·",
            "hardware.keycode.68|º|ª",
            "hardware.keycode.70|¡|¿",
            "hardware.keycode.73|ç|Ç",
            "hardware.keycode.74|ñ|Ñ",
        });
        register(KeyboardLayoutId.PT_QWERTY, new String[] {  // KBDPO, by scan code = US position
            "hardware.keycode.70|«|»",
            "hardware.keycode.74|ç|Ç",
            "hardware.keycode.75|º|ª",
        });
        register(KeyboardLayoutId.IT_QWERTY, new String[] {  // KBDIT, by scan code = US position
            "hardware.keycode.10||£",
            "hardware.keycode.70|ì|",
            "hardware.keycode.71|è|é",
            "hardware.keycode.73|ù|§",
            "hardware.keycode.74|ò|ç",
            "hardware.keycode.75|à|°",
        });
        register(KeyboardLayoutId.TH_KEDMANEE, new String[] {  // KBDTH0, by scan code = US position
            "hardware.key.a|ฟ|ฤ",
            "hardware.key.b|ิ|ฺ",
            "hardware.key.c|แ|ฉ",
            "hardware.key.d|ก|ฏ",
            "hardware.key.e|ำ|ฎ",
            "hardware.key.f|ด|โ",
            "hardware.key.g|เ|ฌ",
            "hardware.key.h|้|็",
            "hardware.key.i|ร|ณ",
            "hardware.key.j|่|๋",
            "hardware.key.k|า|ษ",
            "hardware.key.l|ส|ศ",
            "hardware.key.m|ท|",
            "hardware.key.n|ื|์",
            "hardware.key.o|น|ฯ",
            "hardware.key.p|ย|ญ",
            "hardware.key.q|ๆ|๐",
            "hardware.key.r|พ|ฑ",
            "hardware.key.s|ห|ฆ",
            "hardware.key.t|ะ|ธ",
            "hardware.key.u|ี|๊",
            "hardware.key.v|อ|ฮ",
            "hardware.key.w|ไ|",
            "hardware.key.x|ป|",
            "hardware.key.y|ั|ํ",
            "hardware.key.z|ผ|",
            "hardware.keycode.10||๒",
            "hardware.keycode.11|ภ|๓",
            "hardware.keycode.12|ถ|๔",
            "hardware.keycode.13|ุ|ู",
            "hardware.keycode.14|ึ|฿",
            "hardware.keycode.15|ค|๕",
            "hardware.keycode.16|ต|๖",
            "hardware.keycode.55|ม|ฒ",
            "hardware.keycode.56|ใ|ฬ",
            "hardware.keycode.69|ข|๘",
            "hardware.keycode.70|ช|๙",
            "hardware.keycode.71|บ|ฐ",
            "hardware.keycode.72|ล|",
            "hardware.keycode.73|ฃ|ฅ",
            "hardware.keycode.74|ว|ซ",
            "hardware.keycode.75|ง|",
            "hardware.keycode.76|ฝ|ฦ",
            "hardware.keycode.7|จ|๗",
            "hardware.keycode.8|ๅ|",
            "hardware.keycode.9||๑",
        });
        register(KeyboardLayoutId.HI_INSCRIPT, new String[] {  // KBDINHIN, by scan code = US position
            "hardware.key.a|ो|ओ",
            "hardware.key.b|व|",
            "hardware.key.c|म|ण",
            "hardware.key.d|्|अ",
            "hardware.key.e|ा|आ",
            "hardware.key.f|ि|इ",
            "hardware.key.g|ु|उ",
            "hardware.key.h|प|फ",
            "hardware.key.i|ग|घ",
            "hardware.key.j|र|ऱ",
            "hardware.key.k|क|ख",
            "hardware.key.l|त|थ",
            "hardware.key.m|स|श",
            "hardware.key.n|ल|ळ",
            "hardware.key.o|द|ध",
            "hardware.key.p|ज|झ",
            "hardware.key.q|ौ|औ",
            "hardware.key.r|ी|ई",
            "hardware.key.s|े|ए",
            "hardware.key.t|ू|ऊ",
            "hardware.key.u|ह|ङ",
            "hardware.key.v|न|",
            "hardware.key.w|ै|ऐ",
            "hardware.key.x|ं|ँ",
            "hardware.key.y|ब|भ",
            "hardware.keycode.55||ष",
            "hardware.keycode.56||।",
            "hardware.keycode.69||ः",
            "hardware.keycode.70|ृ|ऋ",
            "hardware.keycode.71|ड|ढ",
            "hardware.keycode.72|़|ञ",
            "hardware.keycode.73|ॉ|ऑ",
            "hardware.keycode.74|च|छ",
            "hardware.keycode.75|ट|ठ",
            "hardware.keycode.76|य|य़",
            "hardware.keycode.8||ऍ",
            "hardware.keycode.9||ॅ",
        });
        register(KeyboardLayoutId.RU_JCUKEN, new String[] {  // KBDRU, by scan code = US position
            "hardware.key.a|ф|Ф",
            "hardware.key.b|и|И",
            "hardware.key.c|с|С",
            "hardware.key.d|в|В",
            "hardware.key.e|у|У",
            "hardware.key.f|а|А",
            "hardware.key.g|п|П",
            "hardware.key.h|р|Р",
            "hardware.key.i|ш|Ш",
            "hardware.key.j|о|О",
            "hardware.key.k|л|Л",
            "hardware.key.l|д|Д",
            "hardware.key.m|ь|Ь",
            "hardware.key.n|т|Т",
            "hardware.key.o|щ|Щ",
            "hardware.key.p|з|З",
            "hardware.key.q|й|Й",
            "hardware.key.r|к|К",
            "hardware.key.s|ы|Ы",
            "hardware.key.t|е|Е",
            "hardware.key.u|г|Г",
            "hardware.key.v|м|М",
            "hardware.key.w|ц|Ц",
            "hardware.key.x|ч|Ч",
            "hardware.key.y|н|Н",
            "hardware.key.z|я|Я",
            "hardware.keycode.10||№",
            "hardware.keycode.55|б|Б",
            "hardware.keycode.56|ю|Ю",
            "hardware.keycode.68|ё|Ё",
            "hardware.keycode.71|х|Х",
            "hardware.keycode.72|ъ|Ъ",
            "hardware.keycode.74|ж|Ж",
            "hardware.keycode.75|э|Э",
        });
        register(KeyboardLayoutId.UK_JCUKEN, new String[] {  // KBDUR, by scan code = US position
            "hardware.key.a|ф|Ф",
            "hardware.key.b|и|И",
            "hardware.key.c|с|С",
            "hardware.key.d|в|В",
            "hardware.key.e|у|У",
            "hardware.key.f|а|А",
            "hardware.key.g|п|П",
            "hardware.key.h|р|Р",
            "hardware.key.i|ш|Ш",
            "hardware.key.j|о|О",
            "hardware.key.k|л|Л",
            "hardware.key.l|д|Д",
            "hardware.key.m|ь|Ь",
            "hardware.key.n|т|Т",
            "hardware.key.o|щ|Щ",
            "hardware.key.p|з|З",
            "hardware.key.q|й|Й",
            "hardware.key.r|к|К",
            "hardware.key.s|і|І",
            "hardware.key.t|е|Е",
            "hardware.key.u|г|Г",
            "hardware.key.v|м|М",
            "hardware.key.w|ц|Ц",
            "hardware.key.x|ч|Ч",
            "hardware.key.y|н|Н",
            "hardware.key.z|я|Я",
            "hardware.keycode.10||№",
            "hardware.keycode.55|б|Б",
            "hardware.keycode.56|ю|Ю",
            "hardware.keycode.68|ё|Ё",
            "hardware.keycode.71|х|Х",
            "hardware.keycode.72|ї|Ї",
            "hardware.keycode.74|ж|Ж",
            "hardware.keycode.75|є|Є",
        });
        register(KeyboardLayoutId.BG_PHONETIC, new String[] {  // KBDBGPH, by scan code = US position
            "hardware.key.a|а|А",
            "hardware.key.b|б|Б",
            "hardware.key.c|ц|Ц",
            "hardware.key.d|д|Д",
            "hardware.key.e|е|Е",
            "hardware.key.f|ф|Ф",
            "hardware.key.g|г|Г",
            "hardware.key.h|х|Х",
            "hardware.key.i|и|И",
            "hardware.key.j|й|Й",
            "hardware.key.k|к|К",
            "hardware.key.l|л|Л",
            "hardware.key.m|м|М",
            "hardware.key.n|н|Н",
            "hardware.key.o|о|О",
            "hardware.key.p|п|П",
            "hardware.key.q|ч|Ч",
            "hardware.key.r|р|Р",
            "hardware.key.s|с|С",
            "hardware.key.t|т|Т",
            "hardware.key.u|у|У",
            "hardware.key.v|в|В",
            "hardware.key.w|ш|Ш",
            "hardware.key.x|ж|Ж",
            "hardware.key.y|ъ|Ъ",
            "hardware.key.z|з|З",
            "hardware.keycode.10||№",
            "hardware.keycode.13||€",
            "hardware.keycode.14||§",
            "hardware.keycode.55||„",
            "hardware.keycode.56||“",
            "hardware.keycode.68|ю|Ю",
            "hardware.keycode.69||–",
            "hardware.keycode.71|я|Я",
            "hardware.keycode.72|щ|Щ",
            "hardware.keycode.73|ь|ѝ",
        });
        register(KeyboardLayoutId.MK_STANDARD, new String[] {  // KBDMACST, by scan code = US position
            "hardware.key.a|а|А",
            "hardware.key.b|б|Б",
            "hardware.key.c|ц|Ц",
            "hardware.key.d|д|Д",
            "hardware.key.e|е|Е",
            "hardware.key.f|ф|Ф",
            "hardware.key.g|г|Г",
            "hardware.key.h|х|Х",
            "hardware.key.i|и|И",
            "hardware.key.j|ј|Ј",
            "hardware.key.k|к|К",
            "hardware.key.l|л|Л",
            "hardware.key.m|м|М",
            "hardware.key.n|н|Н",
            "hardware.key.o|о|О",
            "hardware.key.p|п|П",
            "hardware.key.q|љ|Љ",
            "hardware.key.r|р|Р",
            "hardware.key.s|с|С",
            "hardware.key.t|т|Т",
            "hardware.key.u|у|У",
            "hardware.key.v|в|В",
            "hardware.key.w|њ|Њ",
            "hardware.key.x|џ|Џ",
            "hardware.key.y|ѕ|Ѕ",
            "hardware.key.z|з|З",
            "hardware.keycode.10||“",
            "hardware.keycode.13||‚",
            "hardware.keycode.14||‘",
            "hardware.keycode.68|ѝ|Ѝ",
            "hardware.keycode.71|ш|Ш",
            "hardware.keycode.72|ѓ|Ѓ",
            "hardware.keycode.73|ж|Ж",
            "hardware.keycode.74|ч|Ч",
            "hardware.keycode.75|ќ|Ќ",
            "hardware.keycode.9||„",
        });
        register(KeyboardLayoutId.SR_CYRILLIC, new String[] {  // KBDYCC, by scan code = US position
            "hardware.key.a|а|А",
            "hardware.key.b|б|Б",
            "hardware.key.c|ц|Ц",
            "hardware.key.d|д|Д",
            "hardware.key.e|е|Е",
            "hardware.key.f|ф|Ф",
            "hardware.key.g|г|Г",
            "hardware.key.h|х|Х",
            "hardware.key.i|и|И",
            "hardware.key.j|ј|Ј",
            "hardware.key.k|к|К",
            "hardware.key.l|л|Л",
            "hardware.key.m|м|М",
            "hardware.key.n|н|Н",
            "hardware.key.o|о|О",
            "hardware.key.p|п|П",
            "hardware.key.q|љ|Љ",
            "hardware.key.r|р|Р",
            "hardware.key.s|с|С",
            "hardware.key.t|т|Т",
            "hardware.key.u|у|У",
            "hardware.key.v|в|В",
            "hardware.key.w|њ|Њ",
            "hardware.key.x|џ|Џ",
            "hardware.key.y|з|З",
            "hardware.key.z|ѕ|Ѕ",
            "hardware.keycode.71|ш|Ш",
            "hardware.keycode.72|ђ|Ђ",
            "hardware.keycode.73|ж|Ж",
            "hardware.keycode.74|ч|Ч",
            "hardware.keycode.75|ћ|Ћ",
        });
        register(KeyboardLayoutId.AR_101, new String[] {  // KBDA1, by scan code = US position
            "hardware.key.a|ش|ِ",
            "hardware.key.c|ؤ|",
            "hardware.key.d|ي|",
            "hardware.key.e|ث|ُ",
            "hardware.key.f|ب|",
            "hardware.key.g|ل|",
            "hardware.key.h|ا|أ",
            "hardware.key.i|ه|÷",
            "hardware.key.j|ت|ـ",
            "hardware.key.k|ن|،",
            "hardware.key.l|م|",
            "hardware.key.m|ة|’",
            "hardware.key.n|ى|آ",
            "hardware.key.o|خ|×",
            "hardware.key.p|ح|؛",
            "hardware.key.q|ض|َ",
            "hardware.key.r|ق|ٌ",
            "hardware.key.s|س|ٍ",
            "hardware.key.t|ف|",
            "hardware.key.u|ع|‘",
            "hardware.key.v|ر|",
            "hardware.key.w|ص|ً",
            "hardware.key.x|ء|ْ",
            "hardware.key.y|غ|إ",
            "hardware.key.z|ئ|",
            "hardware.keycode.55|و|",
            "hardware.keycode.56|ز|",
            "hardware.keycode.68|ذ|ّ",
            "hardware.keycode.71|ج|",
            "hardware.keycode.72|د|",
            "hardware.keycode.74|ك|",
            "hardware.keycode.75|ط|",
            "hardware.keycode.76|ظ|؟",
        });
        register(KeyboardLayoutId.UR_PHONETIC, new String[] {  // KBDURDU, by scan code = US position
            "hardware.key.a|م|ژ",
            "hardware.key.b|ش|ؤ",
            "hardware.key.c|ے|ۓ",
            "hardware.key.d|ر|ڑ",
            "hardware.key.e|ھ|ذ",
            "hardware.key.f|ن|ں",
            "hardware.key.g|ل|ۂ",
            "hardware.key.h|ہ|ء",
            "hardware.key.i|ب|ـ",
            "hardware.key.j|ا|آ",
            "hardware.key.k|ک|گ",
            "hardware.key.l|ی|ي",
            "hardware.key.m|ع|‏",
            "hardware.key.n|غ|ئ",
            "hardware.key.o|ج|چ",
            "hardware.key.p|ح|خ",
            "hardware.key.q|ط|ظ",
            "hardware.key.r|د|ڈ",
            "hardware.key.s|و|ز",
            "hardware.key.t|ٹ|ث",
            "hardware.key.u|ت|ۃ",
            "hardware.key.v|س|‎",
            "hardware.key.w|ص|ض",
            "hardware.key.x|ف|‌",
            "hardware.key.y|پ|ّ",
            "hardware.key.z|ق|‍",
            "hardware.keycode.12||٪",
            "hardware.keycode.14||ۖ",
            "hardware.keycode.15||٭",
            "hardware.keycode.55|،|",
            "hardware.keycode.56|۔|",
            "hardware.keycode.74|؛|",
            "hardware.keycode.76||؟",
        });
        register(KeyboardLayoutId.KA_QWERTY, new String[] {  // KBDGEO, by scan code = US position
            "hardware.key.a|ფ|ფ",
            "hardware.key.b|მ|მ",
            "hardware.key.c|ყ|ყ",
            "hardware.key.d|ვ|ვ",
            "hardware.key.e|უ|უ",
            "hardware.key.f|თ|თ",
            "hardware.key.g|ა|ა",
            "hardware.key.h|პ|პ",
            "hardware.key.i|შ|შ",
            "hardware.key.j|რ|რ",
            "hardware.key.k|ო|ო",
            "hardware.key.l|ლ|ლ",
            "hardware.key.m|ტ|ტ",
            "hardware.key.n|ი|ი",
            "hardware.key.o|წ|წ",
            "hardware.key.p|ზ|ზ",
            "hardware.key.q|ღ|ღ",
            "hardware.key.r|კ|კ",
            "hardware.key.s|ძ|ძ",
            "hardware.key.t|ე|ე",
            "hardware.key.u|გ|გ",
            "hardware.key.v|ს|ს",
            "hardware.key.w|ჯ|ჯ",
            "hardware.key.x|ჩ|ჩ",
            "hardware.key.y|ნ|ნ",
            "hardware.key.z|ჭ|ჭ",
            "hardware.keycode.10|№|",
            "hardware.keycode.11|§|",
            "hardware.keycode.55|ქ|ქ",
            "hardware.keycode.56|ბ|ბ",
            "hardware.keycode.68|„|“",
            "hardware.keycode.69|–|",
            "hardware.keycode.71|ხ|ხ",
            "hardware.keycode.72|ც|ც",
            "hardware.keycode.74|დ|დ",
            "hardware.keycode.75|ჟ|ჟ",
            "hardware.keycode.76|ჰ|ჰ",
        });
        register(KeyboardLayoutId.HY_EASTERN, new String[] {  // KBDARME, by scan code = US position
            "hardware.key.a|ա|Ա",
            "hardware.key.b|բ|Բ",
            "hardware.key.c|գ|Գ",
            "hardware.key.d|դ|Դ",
            "hardware.key.e|է|Է",
            "hardware.key.f|ֆ|Ֆ",
            "hardware.key.g|ք|Ք",
            "hardware.key.h|հ|Հ",
            "hardware.key.i|ի|Ի",
            "hardware.key.j|ճ|Ճ",
            "hardware.key.k|կ|Կ",
            "hardware.key.l|լ|Լ",
            "hardware.key.m|մ|Մ",
            "hardware.key.n|ն|Ն",
            "hardware.key.o|ո|Ո",
            "hardware.key.p|պ|Պ",
            "hardware.key.q|խ|Խ",
            "hardware.key.r|ր|Ր",
            "hardware.key.s|ս|Ս",
            "hardware.key.t|տ|Տ",
            "hardware.key.u|ը|Ը",
            "hardware.key.v|վ|Վ",
            "hardware.key.w|ւ|Ւ",
            "hardware.key.x|ց|Ց",
            "hardware.key.y|ե|Ե",
            "hardware.key.z|զ|Զ",
            "hardware.keycode.10|յ|Յ",
            "hardware.keycode.11|՛|",
            "hardware.keycode.14||և",
            "hardware.keycode.15|«|",
            "hardware.keycode.16|»|",
            "hardware.keycode.55|շ|Շ",
            "hardware.keycode.56|ղ|Ղ",
            "hardware.keycode.68|՝|՜",
            "hardware.keycode.69|ռ|Ռ",
            "hardware.keycode.70|ժ|Ժ",
            "hardware.keycode.71|չ|Չ",
            "hardware.keycode.72|ջ|Ջ",
            "hardware.keycode.73||՞",
            "hardware.keycode.74|թ|Թ",
            "hardware.keycode.75|փ|Փ",
            "hardware.keycode.76|ծ|Ծ",
            "hardware.keycode.7|օ|Օ",
            "hardware.keycode.9|ձ|Ձ",
        });
    }

    private HardwareLayoutTables() {
    }

    private static void register(KeyboardLayoutId id, String[] entries) {
        Map<String, String[]> table = new HashMap<>();
        for (String entry : entries) {
            String[] parts = entry.split("\\|", -1);
            table.put(parts[0], new String[] {
                parts[1].isEmpty() ? null : parts[1],
                parts[2].isEmpty() ? null : parts[2]
            });
        }
        TABLES.put(id, table);
    }

    /** The mapper for a layout, or null when the layout has no hardware table here. */
    static HardwareSemanticMapper of(KeyboardLayoutId id) {
        final Map<String, String[]> table = TABLES.get(id);
        if (table == null) {
            return null;
        }
        return (stableKeyId, shift) -> {
            String[] pair = stableKeyId == null ? null : table.get(stableKeyId);
            if (pair == null) {
                return null;
            }
            String text = pair[shift ? 1 : 0];
            return text == null ? null : SemanticInput.text(text);
        };
    }
}
